---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: project-draft-db
          image: mysql:latest         
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10



---
apiVersion: v1
kind: Service
metadata:
  name: project-draft-db
spec:
  selector:
    app: project-draft-db
  ports:
  - port: 3306


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-draft
  labels:
    app: project-draft
spec:
  selector:
    matchLabels:
      app: project-draft
  replicas: 1
  template:
    metadata:
      labels:
        app: project-draft
    spec:
      containers:
        - image: investments:release  
          imagePullPolicy: Never
          name: project-draft
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              value: 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
            - name: OPENAI_MODEL
              value: gpt-4.5
            
---
apiVersion: v1
kind: Service
metadata:
  name: project-draft
spec:
  type: LoadBalancer
  selector:
    app: project-draft
  ports:
    - port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: project-draft-redis
spec:
  selector:
    app: project-draft-redis
  ports:
    - port: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-draft
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: project-draft
                port:
                  number: 8000